# -*- coding: utf-8 -*-
"""Linear_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UENaOvqY-f_CzOU0HnGRd69C31MyEWN5
"""

import numpy as np
import matplotlib.pyplot as plt
import time

# ============================================================
# CLASSES
# ============================================================

class LinearRegressionClosedForm:
    def __init__(self):
        self.w = None
        self.b = None

    def fit(self, X, y):
        X_b = np.c_[np.ones((X.shape[0], 1)), X]
        theta = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y
        self.b = theta[0]
        self.w = theta[1:]

    def predict(self, X):
        return X @ self.w + self.b


class LinearRegressionGD:
    def __init__(self, lr=0.01, max_epochs=5000, tolerance=1e-8):
        self.lr = lr
        self.max_epochs = max_epochs
        self.tolerance = tolerance
        self.w = None
        self.b = None
        self.losses = []
        self.epochs_run = 0

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.w = np.zeros(n_features)
        self.b = 0.0
        self.losses = []
        self.epochs_run = 0
        prev_loss = float("inf")

        for epoch in range(self.max_epochs):
            y_pred = X @ self.w + self.b
            loss = np.mean((y - y_pred) ** 2)
            self.losses.append(loss)
            dw = (-2 / n_samples) * (X.T @ (y - y_pred))
            db = (-2 / n_samples) * np.sum(y - y_pred)
            self.w -= self.lr * dw
            self.b -= self.lr * db
            self.epochs_run += 1
            if abs(prev_loss - loss) < self.tolerance:
                break
            prev_loss = loss

    def predict(self, X):
        return X @ self.w + self.b


def mse(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)


# ============================================================
# BASE DATASET
# ============================================================

np.random.seed(42)
n_samples = 1000
X_base = 2 * np.random.rand(n_samples, 1)
y_base = 4 + 3 * X_base[:, 0] + np.random.randn(n_samples)


# ============================================================
# EXPERIMENT 1: DIFFERENT DATASET SIZES (fixed d=1)
# ============================================================

sizes = [100, 500, 1000, 5000, 10000]
times_closed_n = []
times_gd_n = []
mse_closed_n = []
mse_gd_n = []

print("=" * 65)
print("EXPERIMENT 1: Dataset Size Comparison (d=1, lr=0.1, epochs=1000)")
print("=" * 65)
print(f"{'Size':>8} | {'CF Time':>10} | {'GD Time':>10} | {'CF MSE':>10} | {'GD MSE':>10}")
print("-" * 65)

for n in sizes:
    np.random.seed(42)
    X_t = 2 * np.random.rand(n, 1)
    y_t = 4 + 3 * X_t[:, 0] + np.random.randn(n)

    start = time.time()
    cf = LinearRegressionClosedForm()
    cf.fit(X_t, y_t)
    t_cf = time.time() - start
    m_cf = mse(y_t, cf.predict(X_t))

    start = time.time()
    gd = LinearRegressionGD(lr=0.1, max_epochs=1000, tolerance=1e-12)
    gd.fit(X_t, y_t)
    t_gd = time.time() - start
    m_gd = mse(y_t, gd.predict(X_t))

    times_closed_n.append(t_cf)
    times_gd_n.append(t_gd)
    mse_closed_n.append(m_cf)
    mse_gd_n.append(m_gd)

    print(f"{n:>8} | {t_cf:>10.6f} | {t_gd:>10.6f} | {m_cf:>10.6f} | {m_gd:>10.6f}")


# ============================================================
# EXPERIMENT 2: DIFFERENT FEATURE DIMENSIONS (fixed n=1000)
# ============================================================

dims = [1, 10, 50, 100, 200]
times_closed_d = []
times_gd_d = []
mse_closed_d = []
mse_gd_d = []

print("\n" + "=" * 65)
print("EXPERIMENT 2: Feature Dimension Comparison (n=1000, lr=0.01)")
print("=" * 65)
print(f"{'Dims':>6} | {'CF Time':>10} | {'GD Time':>10} | {'CF MSE':>10} | {'GD MSE':>10}")
print("-" * 65)

for d in dims:
    np.random.seed(42)
    X_t = np.random.rand(1000, d)
    true_w = np.random.randn(d)
    y_t = X_t @ true_w + np.random.randn(1000)

    start = time.time()
    cf = LinearRegressionClosedForm()
    cf.fit(X_t, y_t)
    t_cf = time.time() - start
    m_cf = mse(y_t, cf.predict(X_t))

    start = time.time()
    gd = LinearRegressionGD(lr=0.01, max_epochs=2000, tolerance=1e-8)
    gd.fit(X_t, y_t)
    t_gd = time.time() - start
    m_gd = mse(y_t, gd.predict(X_t))

    times_closed_d.append(t_cf)
    times_gd_d.append(t_gd)
    mse_closed_d.append(m_cf)
    mse_gd_d.append(m_gd)

    print(f"{d:>6} | {t_cf:>10.6f} | {t_gd:>10.6f} | {m_cf:>10.6f} | {m_gd:>10.6f}")


# ============================================================
# EXPERIMENT 3: DIFFERENT LEARNING RATES (fixed n, d)
# ============================================================

learning_rates = [0.0001, 0.001, 0.01, 0.1, 0.5]
lr_results = []

print("\n" + "=" * 70)
print("EXPERIMENT 3: Learning Rate Comparison (n=1000, d=1, early stopping)")
print("=" * 70)
print(f"{'LR':>8} | {'Time (s)':>10} | {'Epochs':>8} | {'Final MSE':>12} | {'Converged':>10}")
print("-" * 70)

for lr in learning_rates:
    gd = LinearRegressionGD(lr=lr, max_epochs=5000, tolerance=1e-8)
    start = time.time()
    gd.fit(X_base, y_base)
    t = time.time() - start
    m = mse(y_base, gd.predict(X_base))
    converged = gd.epochs_run < gd.max_epochs
    lr_results.append((lr, t, gd.epochs_run, m, converged, gd.losses))
    print(f"{lr:>8} | {t:>10.6f} | {gd.epochs_run:>8} | {m:>12.6f} | {'Yes' if converged else 'No':>10}")


# ============================================================
# EXPERIMENT 4: MERGED TABLE (Method + LR comparison)
# ============================================================

print("\n" + "=" * 70)
print("EXPERIMENT 4: Full Merged Comparison")
print("=" * 70)
print(f"{'Method':>8} | {'LR':>8} | {'Time (s)':>10} | {'Epochs':>8} | {'Final MSE':>12}")
print("-" * 70)

cf = LinearRegressionClosedForm()
start = time.time()
cf.fit(X_base, y_base)
t_cf = time.time() - start
m_cf = mse(y_base, cf.predict(X_base))
print(f"{'CF':>8} | {'  -':>8} | {t_cf:>10.6f} | {'1':>8} | {m_cf:>12.6f}")

for lr, t, ep, m, conv, _ in lr_results:
    print(f"{'GD':>8} | {lr:>8} | {t:>10.6f} | {ep:>8} | {m:>12.6f}")


# ============================================================
# PLOTS
# ============================================================

fig, axes = plt.subplots(2, 3, figsize=(16, 10))
fig.suptitle("Linear Regression: Full Comparison", fontsize=14, fontweight='bold')

# Plot 1: Time vs dataset size
ax = axes[0, 0]
ax.plot(sizes, times_closed_n, marker='o', label="Closed Form")
ax.plot(sizes, times_gd_n, marker='o', label="Gradient Descent")
ax.set_xlabel("Dataset Size (n)")
ax.set_ylabel("Time (seconds)")
ax.set_title("Time vs Dataset Size (d=1)")
ax.legend()
ax.grid(True)

# Plot 2: Time vs feature dimension
ax = axes[0, 1]
ax.plot(dims, times_closed_d, marker='o', label="Closed Form")
ax.plot(dims, times_gd_d, marker='o', label="Gradient Descent")
ax.set_xlabel("Number of Features (d)")
ax.set_ylabel("Time (seconds)")
ax.set_title("Time vs Feature Dimension (n=1000)")
ax.legend()
ax.grid(True)

# Plot 3: Loss curves for different learning rates
ax = axes[0, 2]
for lr, t, ep, m, conv, losses in lr_results:
    ax.plot(losses[:300], label=f"lr={lr}")
ax.set_xlabel("Epoch")
ax.set_ylabel("MSE Loss")
ax.set_title("Loss Curve per Learning Rate")
ax.legend()
ax.grid(True)

# Plot 4: Epochs needed per learning rate
ax = axes[1, 0]
lrs_str = [str(r[0]) for r in lr_results]
epochs_list = [r[2] for r in lr_results]
ax.bar(lrs_str, epochs_list, color='steelblue')
ax.set_xlabel("Learning Rate")
ax.set_ylabel("Epochs Needed")
ax.set_title("Epochs Needed per Learning Rate")
ax.grid(True, axis='y')

# Plot 5: Final MSE per learning rate
ax = axes[1, 1]
mse_list = [r[3] for r in lr_results]
ax.bar(lrs_str, mse_list, color='coral')
ax.set_xlabel("Learning Rate")
ax.set_ylabel("Final MSE")
ax.set_title("Final MSE per Learning Rate")
ax.grid(True, axis='y')

# Plot 6: Time per learning rate
ax = axes[1, 2]
time_list = [r[1] for r in lr_results]
ax.bar(lrs_str, time_list, color='mediumseagreen')
ax.set_xlabel("Learning Rate")
ax.set_ylabel("Time (seconds)")
ax.set_title("Execution Time per Learning Rate")
ax.grid(True, axis='y')

plt.tight_layout()

plt.show()